version: '3.1'
services :
  app:
    container_name: cqrssprintboot
    image: cqrssprintboot
    ports:
      - "5000:8080"
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CQRS_proof_of_concept
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
