#docker-compose -f docker-compose-dev.yml -p develoment_CQRS_environment up -d
version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CQRS_proof_of_concept
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 5433:8080
  rabbitmq:
    image: rabbitmq:3.9.13-management
    hostname: my-rabbit
    depends_on:
      - db
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 5434:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo