version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CQRS_proof_of_concept
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 5433:8080
  rabbitmq:
    image: rabbitmq:3.9.13-management
    hostname: my-rabbit
    depends_on:
      - db
    ports:
      - 5672:5672
      - 15672:15672